# Generated by Django 4.0 on 2022-01-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
