# Generated by Django 4.0 on 2022-01-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_purchase_received_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_note',
            field=models.TextField(blank=True),
        ),
    ]
