# Generated by Django 4.0 on 2022-01-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_purchase_purchase_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='shipping',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
