# Generated by Django 4.0 on 2022-01-04 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_purchase_tax_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseItem',
        ),
    ]
