# Generated by Django 4.0 on 2022-01-04 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(max_length=100, verbose_name='Reference No')),
                ('customer_name', models.CharField(max_length=100)),
                ('sell_date', models.DateField()),
                ('order_tax', models.CharField(choices=[('No Tax', 'No Tax'), ('GST@5%', 'GST@5%'), ('VAT%10%', 'VAT@10%')], default='No Tax', max_length=50)),
                ('order_discount', models.PositiveIntegerField(default=0)),
                ('shipping', models.PositiveIntegerField(default=0)),
                ('attachment', models.FileField(blank=True, upload_to='sell')),
                ('sell_status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=50)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Due', 'Due'), ('Paid', 'Paid')], default='Pending', max_length=50)),
                ('sell_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_biller', to='sell.biller')),
            ],
        ),
    ]
