# Generated by Django 4.0 on 2022-01-04 07:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='customer_name',
            field=models.CharField(max_length=100, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='order_discount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Order Discount'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='order_tax',
            field=models.CharField(choices=[('No Tax', 'No Tax'), ('GST@5%', 'GST@5%'), ('VAT%10%', 'VAT@10%')], default='No Tax', max_length=50, verbose_name='Order TAX'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Due', 'Due'), ('Paid', 'Paid')], default='Pending', max_length=50, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='sell_note',
            field=models.TextField(blank=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='sell',
            name='sell_status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=50, verbose_name='Sell Status'),
        ),
    ]
