# Generated by Django 4.0 on 2021-12-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_supplier_created_at_supplier_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Supplier Name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Another Phone Number'),
        ),
    ]
