# Generated by Django 4.0 on 2021-12-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_alter_supplier_name_alter_supplier_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='Country',
        ),
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
